# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = ""
name = ""
application_url = ""
embedded = true
handle = ""

[webhooks]
api_version = "2023-01"

[auth]
redirect_urls = [
  "https:///auth/callback",
  "https:///auth/shopify/callback",
  "https:///api/auth/callback"
]

[pos]
embedded = false
